package com.pixelmarketo.ularo.utility;


import okhttp3.MultipartBody;
import okhttp3.RequestBody;
import okhttp3.ResponseBody;
import retrofit2.Call;
import retrofit2.http.Field;
import retrofit2.http.FormUrlEncoded;
import retrofit2.http.Multipart;
import retrofit2.http.POST;
import retrofit2.http.Part;

public interface LoadInterface {

    @POST("PropertyGetTask")
    @FormUrlEncoded
    Call<ResponseBody> Pro_get_task(@Field(value = "user_id") String name);


    @POST("AddRemarkforProperty")
    @FormUrlEncoded
    Call<ResponseBody> Add_Remark_Pro(@Field(value = "user_id") String userId,
                                      @Field(value = "task_id") String taskId,
                                      @Field(value = "remark") String remark);

    @POST("AddRemarkforVehicle")
    @FormUrlEncoded
    Call<ResponseBody> Add_Remark_Vec(@Field(value = "user_id") String userId,
                                      @Field(value = "task_id") String taskId,
                                      @Field(value = "remark") String remark);


    @POST("AddSumbiltRequest")
    @FormUrlEncoded
    Call<ResponseBody> Submit_request_property(@Field(value = "name") String name,
                                               @Field(value = "user_id") String UserId,
                                               @Field(value = "contact") String contact,
                                               @Field(value = "address") String address,
                                               @Field(value = "landmark") String landmark,
                                               @Field(value = "loan_application_no") String application_no,
                                               @Field(value = "rm_name") String rm_name,
                                               @Field(value = "document_holder") String documentHolder,
                                               @Field(value = "legal_address") String legal_address,
                                               @Field(value = "inspection_date") String inspectionDate,
                                               @Field(value = "word_no") String word,
                                               @Field(value = "vicinity") String vicinity,
                                               @Field(value = "class_type") String class_type,
                                               @Field(value = "condition_approach_road") String condition_approach_road,
                                               @Field(value = "plot_demarcated_at_site") String plot_demarcated_at_site,
                                               @Field(value = "property") String property,
                                               @Field(value = "entire_property_type") String entire_property_type,
                                               @Field(value = "additional_amenities") String additional_amenities,
                                               @Field(value = "premises_type") String premises_type,
                                               @Field(value = "occupied_by") String occupied_by,
                                               @Field(value = "property_rented") String property_rented,
                                               @Field(value = "rent_list_occupants") String rent_list_occupants,
                                               @Field(value = "structure_type") String structure_type,
                                               @Field(value = "no_of_flore") String no_of_flore,
                                               @Field(value = "no_of_wing") String no_of_wing,
                                               @Field(value = "no_of_flat") String no_of_flat,
                                               @Field(value = "internal_composition_of_property") String internal_composition_of_property,
                                               @Field(value = "no_of_lifts") String no_of_lifts,
                                               @Field(value = "property_age") String property_age,
                                               @Field(value = "future_life") String future_life,
                                               @Field(value = "work_quality") String work_quality,
                                               @Field(value = "roofing_terracting") String roofing_terracting,
                                               @Field(value = "quality_of_fixture_fitting") String quality_of_fixture_fitting,
                                               @Field(value = "beam_column_structure") String beam_column_structure,
                                               @Field(value = "maintance_of_building") String maintance_of_building,
                                               @Field(value = "common_area_remark") String common_area_remark,
                                               @Field(value = "reception_area") String reception_area,
                                               @Field(value = "sanitation_facilities") String sanitation_facilities,
                                               @Field(value = "observation") String observation,
                                               @Field(value = "construction_per_approved") String construction_per_approved,
                                               @Field(value = "detail_of_approved_plan") String detail_of_approved_plan,
                                               @Field(value = "violation") String violation,
                                               @Field(value = "plans") String plans,
                                               @Field(value = "land_area_sq_ft") String land_area_sq_ft,
                                               @Field(value = "current_govt_approved") String current_govt_approved,
                                               @Field(value = "recommended_rate") String recommended_rate,
                                               @Field(value = "land_value") String land_value,
                                               @Field(value = "appx_permissible") String appx_permissible,
                                               @Field(value = "bua_premises") String bua_premises,
                                               @Field(value = "present_place_value") String present_place_value,
                                               @Field(value = "value_construction") String value_construction,
                                               @Field(value = "total_valuation") String total_valuation,
                                               @Field(value = "appx_force_sale_value") String appx_force_sale_value,
                                               @Field(value = "valuation_result") String valuation_result,
                                               @Field(value = "remark") String remark,
                                               @Field(value = "recommended_remark") String recommended_remark,
                                               @Field(value = "document_pursued") String document_pursued,
                                               @Field(value = "reference_id") String refrence_id,
                                               @Field(value = "bank_name") String Bank_id,
                                               @Field(value = "proximity_civil_amenities_railway") String proximity_civil_amenities_railway,
                                               @Field(value = " proximity_civil_amenities_bus_stop") String proximity_civil_amenities_bus_stop,
                                               @Field(value = " proximity_civil_amenities_hostpital") String proximity_civil_amenities_hostpital,
                                               @Field(value = " proximity_civil_amenities_landmark") String proximity_civil_amenities_landmark,
                                               @Field(value = " boundaries_per_site_east") String boundaries_per_site_east,
                                               @Field(value = " boundaries_per_site_west") String boundaries_per_site_west,
                                               @Field(value = " boundaries_per_site_north") String boundaries_per_site_north,
                                               @Field(value = " boundaries_per_site_south") String boundaries_per_site_south,
                                               @Field(value = " boundaries_per_doc_east") String boundaries_per_doc_east,
                                               @Field(value = " boundaries_per_doc_west") String boundaries_per_doc_west,
                                               @Field(value = " boundaries_per_doc_north") String boundaries_per_doc_north,
                                               @Field(value = " boundaries_per_doc_south") String boundaries_per_doc_south,
                                               @Field(value = "declaration") String declaration);

    @POST("vehicleGetTask")
    @FormUrlEncoded
    Call<ResponseBody> Veic_get_task(@Field(value = "user_id") String userId);


    @POST("SubmitVehicleDetail")
    @FormUrlEncoded
    Call<ResponseBody> SubmitVehicleDetail(@Field(value = "user_id") String user_id,
                                           @Field(value = "borrowers_detail") String borrowers_detail,
                                           @Field(value = "borrowers_max_score") String borrowers_max_score,
                                           @Field(value = "borrowers_actual_score") String borrowers_actual_score,
                                           @Field(value = "borrowers_remark") String borrowers_remark,
                                           @Field(value = "inspection_detail") String inspection_detail,
                                           @Field(value = "inspection_max_score") String inspection_max_score,
                                           @Field(value = "inspection_actual_score") String inspection_actual_score,
                                           @Field(value = "inspection_remark") String inspection_remark,
                                           @Field(value = "vehicle_detail") String vehicle_detail,
                                           @Field(value = "vehicle_max_score") String vehicle_max_score,
                                           @Field(value = "vehicle_actual_score") String vehicle_actual_score,
                                           @Field(value = "vehicle_remark") String vehicle_remark,
                                           @Field(value = "place_inspection_detail") String place_inspection_detail,
                                           @Field(value = "place_inspection_max_score") String place_inspection_max_score,
                                           @Field(value = "place_inspection_actual_score") String place_inspection_actual_score,
                                           @Field(value = "place_inspection_remark") String place_inspection_remark,
                                           @Field(value = "inspection_contact") String inspection_contact,
                                           @Field(value = "owner_detail") String owner_detail,
                                           @Field(value = "owner_max_score") String owner_max_score,
                                           @Field(value = "owner_actual_score") String owner_actual_score,
                                           @Field(value = "owner_remark") String owner_remark,
                                           @Field(value = "vehicle_reg_detail") String vehicle_reg_detail,
                                           @Field(value = "vehicle_reg_max_score") String vehicle_reg_max_score,
                                           @Field(value = "vehicle_reg_actual_score") String vehicle_reg_actual_score,
                                           @Field(value = "vehicle_reg_remark") String vehicle_reg_remark,
                                           @Field(value = "hypothecation_detail") String hypothecation_detail,
                                           @Field(value = "hypothecation_max_score") String hypothecation_max_score,
                                           @Field(value = "hypothecation_actual_score") String hypothecation_actual_score,
                                           @Field(value = "hypothecation_remark") String hypothecation_remark,
                                           @Field(value = "reg_date_detail") String reg_date_detail,
                                           @Field(value = "reg_date_max_score") String reg_date_max_score,
                                           @Field(value = "reg_date_actual_score") String reg_date_actual_score,
                                           @Field(value = "reg_date_remark") String reg_date_remark,
                                           @Field(value = "vehicle_model_detail") String vehicle_model_detail,
                                           @Field(value = "vehicle_model_max_score") String vehicle_model_max_score,
                                           @Field(value = "vehicle_model_actual_score") String vehicle_model_actual_score,
                                           @Field(value = "vehicle_model_remark") String vehicle_model_remark,
                                           @Field(value = "manufacturing_detail") String manufacturing_detail,
                                           @Field(value = "manufacturing_max_score") String manufacturing_max_score,
                                           @Field(value = "manufacturing_actual_score") String manufacturing_actual_score,
                                           @Field(value = "manufacturing_remark") String manufacturing_remark,
                                           @Field(value = "owner_serial_no_detail") String owner_serial_no_detail,
                                           @Field(value = "owner_serial_no_max_score") String owner_serial_no_max_score,
                                           @Field(value = "owner_serial_no_actual_score") String owner_serial_no_actual_score,
                                           @Field(value = "owner_serial_no_remark") String owner_serial_no_remark,
                                           @Field(value = "insurance_policy_detail") String insurance_policy_detail,
                                           @Field(value = "insurance_policy_max_score") String insurance_policy_max_score,
                                           @Field(value = "insurance_policy_actual_score") String insurance_policy_actual_score,
                                           @Field(value = "insurance_policy_remark") String insurance_policy_remark,
                                           @Field(value = "comprehensive_detail") String comprehensive_detail,
                                           @Field(value = "comprehensive_max_score") String comprehensive_max_score,
                                           @Field(value = "comprehensive_actual_score") String comprehensive_actual_score,
                                           @Field(value = "comprehensive_remark") String comprehensive_remark,
                                           @Field(value = "meter_reading_detail") String meter_reading_detail,
                                           @Field(value = "meter_reading_max_score") String meter_reading_max_score,
                                           @Field(value = "meter_reading_actual_score") String meter_reading_actual_score,
                                           @Field(value = "meter_reading_remark") String meter_reading_remark,
                                           @Field(value = "colour_seating_detail") String colour_seating_detail,
                                           @Field(value = "colour_seating_max_score") String colour_seating_max_score,
                                           @Field(value = "colour_seating_actual_score") String colour_seating_actual_score,
                                           @Field(value = "colour_seating_remark") String colour_seating_remark,
                                           @Field(value = "cubic_capacity_detail") String cubic_capacity_detail,
                                           @Field(value = "cubic_capacity_max_score") String cubic_capacity_max_score,
                                           @Field(value = "cubic_capacity_actual_score") String cubic_capacity_actual_score,
                                           @Field(value = "cubic_capacity_actual_remark") String cubic_capacity_actual_remark,
                                           @Field(value = "engine_no_detail") String engine_no_detail,
                                           @Field(value = "engine_no_max_score") String engine_no_max_score,
                                           @Field(value = "engine_no_actual_score") String engine_no_actual_score,
                                           @Field(value = "engine_no_remark") String engine_no_remark,
                                           @Field(value = "chassis_detail") String chassis_detail,
                                           @Field(value = "chassis_max_score") String chassis_max_score,
                                           @Field(value = "chassis_actual_score") String chassis_actual_score,
                                           @Field(value = "chassis_remark") String chassis_remark,
                                           @Field(value = "class_fuel_detail") String class_fuel_detail,
                                           @Field(value = "class_fuel_max_score") String class_fuel_max_score,
                                           @Field(value = "class_fuel_actual_score") String class_fuel_actual_score,
                                           @Field(value = "class_fuel_remark") String class_fuel_remark,
                                           @Field(value = "life_time_tax_detail") String life_time_tax_detail,
                                           @Field(value = "life_time_tax_max_score") String life_time_tax_max_score,
                                           @Field(value = "life_time_tax_actual_score") String life_time_tax_actual_score,
                                           @Field(value = "life_time_tax_remark") String life_time_tax_remark,
                                           @Field(value = "use_vehicle_detail") String use_vehicle_detail,
                                           @Field(value = "use_vehicle_max_score") String use_vehicle_max_score,
                                           @Field(value = "use_vehicle_actual_score") String use_vehicle_actual_score,
                                           @Field(value = "use_vehicle_remark") String use_vehicle_remark,
                                           @Field(value = "no_plate_detail") String no_plate_detail,
                                           @Field(value = "no_plate_max_score") String no_plate_max_score,
                                           @Field(value = "no_plate_actual_score") String no_plate_actual_score,
                                           @Field(value = "no_plate_remark") String no_plate_remark,
                                           @Field(value = "model_currently_detail") String model_currently_detail,
                                           @Field(value = "model_currently_max_score") String model_currently_max_score,
                                           @Field(value = "model_currently_actual_score") String model_currently_actual_score,
                                           @Field(value = "model_currently_remark") String model_currently_remark,
                                           @Field(value = "air_conditioner_detail") String air_conditioner_detail,
                                           @Field(value = "air_conditioner_max_score") String air_conditioner_max_score,
                                           @Field(value = "air_conditioner_actual_score") String air_conditioner_actual_score,
                                           @Field(value = "air_conditioner_remark") String air_conditioner_remark,
                                           @Field(value = "tool_kit_detail") String tool_kit_detail,
                                           @Field(value = "tool_kit_max_score") String tool_kit_max_score,
                                           @Field(value = "tool_kit_actual_score") String tool_kit_actual_score,
                                           @Field(value = "tool_kit_remark") String tool_kit_remark,
                                           @Field(value = "engine_detail") String engine_detail,
                                           @Field(value = "engine_max_score") String engine_max_score,
                                           @Field(value = "engine_actual_score") String engine_actual_score,
                                           @Field(value = "engine_remark") String engine_remark,
                                           @Field(value = "battery_detail") String battery_detail,
                                           @Field(value = "battery_max_score") String battery_max_score,
                                           @Field(value = "battery_actual_score") String battery_actual_score,
                                           @Field(value = "battery_remark") String battery_remark,
                                           @Field(value = "steering_detail") String steering_detail,
                                           @Field(value = "steering_max_score") String steering_max_score,
                                           @Field(value = "steering_actual_score") String steering_actual_score,
                                           @Field(value = "steering_remark") String steering_remark,
                                           @Field(value = "rh_frt_make") String rh_frt_make,
                                           @Field(value = "rh_frt_condition") String rh_frt_condition,
                                           @Field(value = "lh_frt_make") String lh_frt_make,
                                           @Field(value = "lh_frt_condition") String lh_frt_condition,
                                           @Field(value = "rh_rr_make") String rh_rr_make,
                                           @Field(value = "rh_rr_condition") String rh_rr_condition,
                                           @Field(value = "lh_rr_make") String lh_rr_make,
                                           @Field(value = "lh_rr_condition") String lh_rr_condition,
                                           @Field(value = "spare_wheel_make") String spare_wheel_make,
                                           @Field(value = "spare_wheel_condition") String spare_wheel_condition,
                                           @Field(value = "accident_detail") String accident_detail,
                                           @Field(value = "accident_max_score") String accident_max_score,
                                           @Field(value = "accident_actual_score") String accident_actual_score,
                                           @Field(value = "accident_remark") String accident_remark,
                                           @Field(value = "major_repair_detail") String major_repair_detail,
                                           @Field(value = "major_repair_max_score") String major_repair_max_score,
                                           @Field(value = "major_repair_actual_score") String major_repair_actual_score,
                                           @Field(value = "major_repair_remark") String major_repair_remark,
                                           @Field(value = "ovarall_rating_detail") String ovarall_rating_detail,
                                           @Field(value = "ovarall_rating_max_score") String ovarall_rating_max_score,
                                           @Field(value = "ovarall_rating_actual_score") String ovarall_rating_actual_score,
                                           @Field(value = "ovarall_rating_remark") String ovarall_rating_remark,
                                           @Field(value = "rto_detail") String rto_detail,
                                           @Field(value = "rto_max_score") String rto_max_score,
                                           @Field(value = "rto_actual_score") String rto_actual_score,
                                           @Field(value = "rto_actual_remark") String rto_actual_remark,
                                           @Field(value = "docs_verify_detail") String docs_verify_detail,
                                           @Field(value = "docs_verify_max_score") String docs_verify_max_score,
                                           @Field(value = "docs_verify_actual_score") String docs_verify_actual_score,
                                           @Field(value = "docs_verify_remark") String docs_verify_remark,
                                           @Field(value = "reg_book_detail") String reg_book_detail,
                                           @Field(value = "reg_book_max_score") String reg_book_max_score,
                                           @Field(value = "reg_book_actual_score") String reg_book_actual_score,
                                           @Field(value = "reg_book_remark") String reg_book_remark,
                                           @Field(value = "insurance_paper_detail") String insurance_paper_detail,
                                           @Field(value = "insurance_paper_max_score") String insurance_paper_max_score,
                                           @Field(value = "insurance_paper_actual_score") String insurance_paper_actual_score,
                                           @Field(value = "insurance_paper_remark") String insurance_paper_remark,
                                           @Field(value = "remark_detail") String remark_detail,
                                           @Field(value = "remark_max_score") String remark_max_score,
                                           @Field(value = "remark_actual_score") String remark_actual_score,
                                           @Field(value = "remark") String remark,
                                           @Field(value = "vehicle_photograp_detail") String vehicle_photograp_detail,
                                           @Field(value = "vehicle_photograp_max_score") String vehicle_photograp_max_score,
                                           @Field(value = "vehicle_photograp_actual_score") String vehicle_photograp_actual_score,
                                           @Field(value = "vehicle_photograp_remark") String vehicle_photograp_remark,
                                           @Field(value = "chassis_print_detail") String chassis_print_detail,
                                           @Field(value = "chassis_print_max_score") String chassis_print_max_score,
                                           @Field(value = "chassis_print_actual_score") String chassis_print_actual_score,
                                           @Field(value = "chassis_print_remark") String chassis_print_remark,
                                           @Field(value = "particular_rto_detail") String particular_rto_detail,
                                           @Field(value = "particular_rto_max_score") String particular_rto_max_score,
                                           @Field(value = "particular_rto_actual_score") String particular_rto_actual_score,
                                           @Field(value = "particular_rto_remark") String particular_rto_remark,
                                           @Field(value = "current_value_car") String current_value_car,
                                           @Field(value = "requisition_max_score") String requisition_max_score,
                                           @Field(value = "requisition_actual_score") String requisition_actual_score,
                                           @Field(value = "inspection_detail_max_score") String inspection_detail_max_score,
                                           @Field(value = "inspection_detail_actual_score") String inspection_detail_actual_score,
                                           @Field(value = "title_max_score") String title_max_score,
                                           @Field(value = "title_actual_score") String title_actual_score,
                                           @Field(value = "vehicle_specification_max_score") String vehicle_specification_max_score,
                                           @Field(value = "vehicle_specification_actual_score") String vehicle_specification_actual_score,
                                           @Field(value = "regulation_max_score") String regulation_max_score,
                                           @Field(value = "regulation_actual_score") String regulation_actual_score,
                                           @Field(value = "physical_condition_car_max_value") String physical_condition_car_max_value,
                                           @Field(value = "physical_condition_car_actual_value") String physical_condition_car_actual_value,
                                           @Field(value = "other_remark_max_score") String other_remark_max_score,
                                           @Field(value = "other_remark_actual_score") String other_remark_actual_score,
                                           @Field(value = "enclosures_max_score") String enclosures_max_score,
                                           @Field(value = "enclosures_actual_score") String enclosures_actual_score,
                                           @Field(value = "reference_id") String reference_id,
                                           @Field(value = "bank_name") String bank_name);


    @POST("user_login")
    @FormUrlEncoded
    Call<ResponseBody> user_Login(@Field(value = "user_contact") String contact,
                                  @Field(value = "password") String password,
                                  @Field(value = "deviceId") String device_id,
                                  @Field(value = "deviceType") String deviceType,
                                  @Field(value = "imei") String imei);


    @Multipart
    @POST("UpdateProfile")
    Call<ResponseBody> UpdateProfile_admin(@Part(value = "user_id") RequestBody user_id,
                                           @Part(value = "user_name") RequestBody user_name,
                                           @Part(value = "email") RequestBody email,
                                           @Part(value = "contact") RequestBody contact,
                                           @Part MultipartBody.Part file1);

    @Multipart
    @POST("UpdateProfile")
    Call<ResponseBody> UpdateProfile_No_Image(@Part(value = "user_id") RequestBody user_id,
                                              @Part(value = "user_name") RequestBody user_name,
                                              @Part(value = "email") RequestBody email,
                                              @Part(value = "contact") RequestBody contact);

    @POST("delete_history")
    @FormUrlEncoded
    Call<ResponseBody> delete_history(@Field(value = "id") String id);

    @Multipart
    @POST("PropertyImage")
    Call<ResponseBody> propertyImages(@Part("user_id") RequestBody userid,
                                      @Part MultipartBody.Part file,
                                      @Part MultipartBody.Part file1,
                                      @Part MultipartBody.Part file2,
                                      @Part MultipartBody.Part file3,
                                      @Part MultipartBody.Part file4,
                                      @Part MultipartBody.Part file5,
                                      @Part MultipartBody.Part file6,
                                      @Part MultipartBody.Part file7,
                                      @Part MultipartBody.Part[] imageArray);

    @Multipart
    @POST("PropertyImage")
    Call<ResponseBody> propertyImages_without_otherimages(@Part("user_id") RequestBody userid,
                                                          @Part MultipartBody.Part file,
                                                          @Part MultipartBody.Part file1,
                                                          @Part MultipartBody.Part file2,
                                                          @Part MultipartBody.Part file3,
                                                          @Part MultipartBody.Part file4,
                                                          @Part MultipartBody.Part file5,
                                                          @Part MultipartBody.Part file6,
                                                          @Part MultipartBody.Part file7);

    @Multipart
    @POST("VehicleImage")
    Call<ResponseBody> veichleImg(@Part("user_id") RequestBody userid, @Part MultipartBody.Part file,
                                  @Part MultipartBody.Part file1,
                                  @Part MultipartBody.Part file2,
                                  @Part MultipartBody.Part file3,
                                  @Part MultipartBody.Part file4,
                                  @Part MultipartBody.Part file5,
                                  @Part MultipartBody.Part file6,
                                  @Part MultipartBody.Part file7,
                                  @Part MultipartBody.Part file8,
                                  @Part MultipartBody.Part file9,
                                  @Part MultipartBody.Part file10,
                                  @Part MultipartBody.Part file11,
                                  @Part MultipartBody.Part file12,
                                  @Part MultipartBody.Part file13,
                                  @Part MultipartBody.Part file14,
                                  @Part MultipartBody.Part file15,
                                  @Part MultipartBody.Part file16,
                                  @Part MultipartBody.Part file17,
                                  @Part MultipartBody.Part file18,
                                  @Part MultipartBody.Part file19,
                                  @Part MultipartBody.Part file20,
                                  @Part MultipartBody.Part file21,
                                  @Part MultipartBody.Part file22,
                                  @Part MultipartBody.Part file23,
                                  @Part MultipartBody.Part file24);

    @Multipart
    @POST("VehicleImage")
    Call<ResponseBody> veichleImg_other(@Part("user_id") RequestBody userid, @Part MultipartBody.Part file,
                                        @Part MultipartBody.Part file1,
                                        @Part MultipartBody.Part file2,
                                        @Part MultipartBody.Part file3,
                                        @Part MultipartBody.Part file4,
                                        @Part MultipartBody.Part file5,
                                        @Part MultipartBody.Part file6,
                                        @Part MultipartBody.Part file7,
                                        @Part MultipartBody.Part file8,
                                        @Part MultipartBody.Part file9,
                                        @Part MultipartBody.Part file10,
                                        @Part MultipartBody.Part file11,
                                        @Part MultipartBody.Part file12,
                                        @Part MultipartBody.Part file13,
                                        @Part MultipartBody.Part file14,
                                        @Part MultipartBody.Part file15,
                                        @Part MultipartBody.Part file16,
                                        @Part MultipartBody.Part file17,
                                        @Part MultipartBody.Part file18,
                                        @Part MultipartBody.Part file19,
                                        @Part MultipartBody.Part file20,
                                        @Part MultipartBody.Part file21,
                                        @Part MultipartBody.Part file22,
                                        @Part MultipartBody.Part file23,
                                        @Part MultipartBody.Part file24,
                                        @Part MultipartBody.Part[] surveyImage);

}